---
- name: Install Minikube with Helm
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64
        dest: /usr/local/bin/minikube
        mode: "0755"

    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.29.0/bin/linux/arm64/kubectl
        dest: /usr/local/bin/kubectl
        mode: "0755"

    - name: Download Helm
      get_url:
        url: https://get.helm.sh/helm-v3.14.0-linux-arm64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Extract Helm
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Install Helm
      copy:
        src: /tmp/linux-arm64/helm
        dest: /usr/local/bin/helm
        mode: "0755"
        remote_src: yes

    - name: Reset SSH connection
      meta: reset_connection

    - name: Start Minikube
      become: true
      become_user: vagrant
      shell: |
        sg docker -c "minikube start --driver=docker --memory=4096 --cpus=2"
      args:
        creates: /home/vagrant/.minikube

    - name: Add Helm repos from ArtifactHub
      become: true
      become_user: vagrant
      command: "{{ item }}"
      loop:
        - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        - helm repo add minio https://charts.min.io
        - helm repo add grafana https://grafana.github.io/helm-charts
        - helm repo update
      changed_when: false
